apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: sample
spec:
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample-container
        image: nginxdemos/hello
  replicas: 3
  selector:
    matchLabels:
      app: sample
