apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  namespace: go-mysql-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
      tier: data   
  template:
    metadata:
      labels:
        app: mysql-server
        tier: data
    spec:
      containers:
      - name: mysql-server
        image: 192.168.8.1:6000/mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: go-mysql-api-env-vars-secrets
              key: DB_PASS
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv
        hostPath: 
          path: /data
          type: Directory
    