apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-mysql-api
  namespace: go-mysql-api
  labels:
    app: go-mysql-api
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-mysql-api
      tier: web
  template:
    metadata:
      labels:
        app: go-mysql-api
        tier: web
    spec:
      initContainers:
      - name: create-db-schema
        image: 192.168.8.1:6000/go-mysql-api-init-container-image:debian
        volumeMounts:
        - name: init-sql-script
          mountPath: /sql_script/script.sql
          subPath: script.sql
        command: ["/bin/bash","-c","mysql -u $(DB_USER) -p$(DB_PASS) -h $(DB_HOST) -P $(DB_PORT) < script.sql"]
        # command: ["cat","/etc/resolv.conf"]
        envFrom:
        - configMapRef:
            name: go-mysql-api-env-vars
        - secretRef:
            name: go-mysql-api-env-vars-secrets
      containers:
      - name: go-mysql-api
        image: 192.168.8.1:6000/go-mysql-api
        envFrom:
        - configMapRef:
            name: go-mysql-api-env-vars
        - secretRef:
            name: go-mysql-api-env-vars-secrets
      volumes:
      - name: init-sql-script
        configMap:
          name: init-sql-script
