apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-mysql-api-deployment
  namespace: go-mysql-api
  labels:
    app: go-mysql-api
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-mysql-api
      tier: web
  template:
    metadata:
      labels:
        app: go-mysql-api
        tier: web
    spec:
      initContainers:
      - name: create-db-schema
        image: jvin911/janiths-public-repo:go-mysql-api-init-image
        imagePullPolicy: Always
        volumeMounts:
        - name: init-sql-script
          mountPath: /sql_script/script.sql
          subPath: script.sql
        args:
        - "/sql_script/script.sql"
        envFrom:
        - configMapRef:
            name: go-mysql-api-env-vars
        - secretRef:
            name: go-mysql-api-env-vars-secrets
        restartPolicy: OnFailure
      containers:
      - name: go-mysql-api
        image: jvin911/janiths-public-repo:go-mysql-api
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: go-mysql-api-env-vars
        - secretRef:
            name: go-mysql-api-env-vars-secrets
      volumes:
      - name: init-sql-script
        configMap:
          name: init-sql-script
